name: marvel_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter

  # Stream
  stream_transform: ^2.1.0
  rxdart: ^0.27.7

  # BLoC
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2

  # Networking
  dio: ^5.3.3

  # Persisting
  drift: ^2.13.1
  drift_sqflite: ^2.0.1

  # Utils
  path: ^1.8.3
  path_provider: ^2.1.0
  crypto: ^3.0.3
  auto_route: ^7.8.4
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  sizzle_lints: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^2.0.0

  # Utils
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  intl_utils: ^2.8.5
  flutter_native_splash: ^2.3.5

  # Codegen
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  drift_dev: ^2.13.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
