// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCyEuYTZl_iyjzuNUvH09U7dZzTK5APFo',
    appId: '1:1092924658125:web:fd5adf5f2b15f991983484',
    messagingSenderId: '1092924658125',
    projectId: 'marvelapp-b1c51',
    authDomain: 'marvelapp-b1c51.firebaseapp.com',
    storageBucket: 'marvelapp-b1c51.appspot.com',
    measurementId: 'G-192L6B7430',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrxqysYRwHwW-BTomvyjigR5QVy8fepWY',
    appId: '1:1092924658125:android:dc7377dbd54f5e92983484',
    messagingSenderId: '1092924658125',
    projectId: 'marvelapp-b1c51',
    storageBucket: 'marvelapp-b1c51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxFaHQyfUt2SkB1cyEmZ7KZKABa4AaZjI',
    appId: '1:1092924658125:ios:20d2f9457e4c6fb8983484',
    messagingSenderId: '1092924658125',
    projectId: 'marvelapp-b1c51',
    storageBucket: 'marvelapp-b1c51.appspot.com',
    iosBundleId: 'com.example.marvelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxFaHQyfUt2SkB1cyEmZ7KZKABa4AaZjI',
    appId: '1:1092924658125:ios:cc27267d8c25b57a983484',
    messagingSenderId: '1092924658125',
    projectId: 'marvelapp-b1c51',
    storageBucket: 'marvelapp-b1c51.appspot.com',
    iosBundleId: 'com.example.marvelApp.RunnerTests',
  );
}
